<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO0e4oFN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO0e4oFN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO0e4oFN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO0e4oFN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO0e4oFN\App_KernelDevDebugContainer([
    'container.build_hash' => 'O0e4oFN',
    'container.build_id' => '30cd8091',
    'container.build_time' => 1583674366,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO0e4oFN');
