<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXAfhKDs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXAfhKDs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXAfhKDs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXAfhKDs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXAfhKDs\App_KernelDevDebugContainer([
    'container.build_hash' => 'XAfhKDs',
    'container.build_id' => '8c52cb42',
    'container.build_time' => 1583683178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXAfhKDs');
